### ISSUE TITLE
安装vmr时获取系统变量SHELL为空导致空指针异常

### ISSUE THREAD

**Issue by kaizi2009** [gvcgo/version-manager#127]
## Platform Info
debian的docker镜像（docker pull debian）
```shell
root@74c466197ea8:/# uname
Linux

root@74c466197ea8:/# uname -m
aarch64

root@74c466197ea8:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@74c466197ea8:/# echo $SHELL
/bin/bash
```

## Description
安装vmr（curl --proto '=https' --tlsv1.2 -sSf https://scripts.vmr.us.kg | sh）时，
空指针异常，shellPath := os.Getenv("SHELL")，shellPath没有获取到。
但echo $SHELL可以获取到

## Screen Shot
异常信息如下：
```go
Installing...
Archive:  ./vmr_linux-arm64.zip
  inflating: vmr                     
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x53ca60]

goroutine 1 [running]:
https://[github.com/gvcgo/version-manager/internal/self.InstallSelf()](https://github.com/gvcgo/version-manager/internal/self.InstallSelf()) 
        D:/projects/go/src/gogvc/version-manager/internal/self/install.go:46 +0x110
github.com/gvcgo/version-manager/cmd/vmr/cli.init.func3(0x4000170c00?, {0x652473?, 0x4?, 0x65243f?})
        D:/projects/go/src/gogvc/version-manager/cmd/vmr/cli/install_self.go:20 +0x1c
github.com/spf13/cobra.(*Command).execute(0xc10780, {0xc825c0, 0x0, 0x0})
        D:/projects/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
https://[github.com/spf13/cobra.(*Command).ExecuteC(0x400035a308)](https://github.com/spf13/cobra.(*Command).ExecuteC(0x400035a308)) 
        D:/projects/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
https://[github.com/spf13/cobra.(*Command).Execute(...)](https://github.com/spf13/cobra.(*Command).Execute(...)) 
        D:/projects/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
https://[github.com/gvcgo/version-manager/cmd/vmr/cli.(*Cli).Run(0x75ffd8?)](https://github.com/gvcgo/version-manager/cmd/vmr/cli.(*Cli).Run(0x75ffd8?)) 
        D:/projects/go/src/gogvc/version-manager/cmd/vmr/cli/cli.go:71 +0x20
main.main()
        D:/projects/go/src/gogvc/version-manager/cmd/vmr/main.go:40 +0x40
```

**Comment by moqsien** [comment]
目前没试过在docker容器中跑VMR。

从堆栈来看，是WriteVMEnvToShell方法报错了，应该是获取shell类型失败了，然后shell对象初始化成nil了。你有环境，可以测试一下在debian docker镜像中，go的os.Getenv("SHELL")能不能获取到SHELL这个环境变量？

**Comment by kaizi2009** [comment]
我用源码在docker中运行了，os.Getenv("SHELL")获取不到，我已经提交了一个PR, 可以解决问题

**Comment by kaizi2009** [comment]
进程访问系统的变量，会有多种原因导致访问不到，可以在启动时export变量，确保稳定

**Comment by moqsien** [comment]
> 进程访问系统的变量，会有多种原因导致访问不到，可以在启动时export变量，确保稳定

这个可以有。因为没在docker下跑过VMR，还没发现获取不到$SHELL，环境变量这块，是由 @zzhaolei  大佬重构的，确实没有这种使用场景。感谢提出并修复bug。

preview这个脚本也可以添加一下，https://github.com/gvcgo/version-manager/blob/main/scripts/install.preview.sh

可以一并提交。

**Comment by moqsien** [comment]
> 进程访问系统的变量，会有多种原因导致访问不到，可以在启动时export变量，确保稳定

但是，还有个问题。在VMR的session模式中，也会用到$SHELL，这是不是在使用过程中也需要export?

**Comment by moqsien** [comment]
https://github.com/gvcgo/version-manager/blob/main/scripts/install.preview.sh
改好了。

**Comment by kaizi2009** [comment]
先暂时通过export解决，我再看看有没有更好的办法

**Comment by kaizi2009** [comment]
有没有开发群，邀请我一下？有些想法想沟通一下 ，个人邮箱：kaizi_2009@126.com
@moqsien

**Comment by moqsien** [comment]
> 有没有开发群，邀请我一下？有些想法想沟通一下 ，个人邮箱：[kaizi_2009@126.com](mailto:kaizi_2009@126.com) @moqsien

目前没有。我邀请你加入开发者组吧。

**Comment by moqsien** [comment]
> 先暂时通过export解决，我再看看有没有更好的办法

我想到一个办法，就是和另外一个方法一样，设置一个fallback，例如最常用的默认shell，“/bin/bash”
